a = int(input("Enter the first number:"))
b = int(input("Enter the second number"))
print("Addition:",a+b)
a = int(input("Enter the first number:"))
b = int(input("Enter the second number"))
print("Subtraction:",a-b)
a = int(input("Enter the first number:"))
b = int(input("Enter the second number"))
print("Multiplication:",a*b)
a = int(input("Enter the first number:"))
b = int(input("Enter the second number"))
print("Division:",a/b)
a = int(input("Enter the first number:"))
b = int(input("Enter the second number"))
print("Module:",a%b)

